#include "..\far\plugin.hpp"

#define PLUGIN_VER_MAJOR   3
#define PLUGIN_VER_MINOR   46
#define PLUGIN_VER_BUILD   9
#define PLUGIN_FAR_BUILD   4362

//Версия сборки плагина
#define PLUGIN_BUILD 0

#define PLUGIN_NAME        "Portrait"
#define PLUGIN_AUTHOR      "NSTU FAMI 2021"
#define PLUGIN_DESCR       "Portrait Matrix Plugin for Far Manager"
#define PLUGIN_FILENAME    "Portrait.dll"

#define VSTR__(v) #v
#define VSTR(v) VSTR__(v)

#define PLUGIN_VERSION_NUM    PLUGIN_VER_MAJOR,PLUGIN_VER_MINOR,PLUGIN_VER_BUILD,PLUGIN_FAR_BUILD
#define PLUGIN_VERSION_NUM_RC PLUGIN_VER_MAJOR,PLUGIN_VER_MINOR,PLUGIN_FAR_BUILD,PLUGIN_VER_BUILD
#define PLUGIN_VERSION_TXT_RC VSTR(PLUGIN_VER_MAJOR) "." VSTR(PLUGIN_VER_MINOR) "." VSTR(PLUGIN_FAR_BUILD) "." VSTR(PLUGIN_VER_BUILD)